# 前言

Promise 的基本使用可以看阮一峰老师的[《ECMAScript 6》](http://es6.ruanyifeng.com/#docs/promise)

## 回调

说起 Promise，一般都会从回调或者回调地狱说起，那么回调到底会导致哪些不好的地方呢？

### 回调嵌套

使用回调，很有可能会将业务代码写成如下这种形式:

```js
doA(function () {
	doB()

	doC(function () {
		doD()
	})

	doE()
})

doF()
```

当然这是一种简化的形式，经过一番简单的思考，可以判断出执行的顺序为:

```
doA()
doF()
doB()
doC()
doE()
doD()
```

然而在实际的项目中，代码会更加杂乱，为了排查问题，需要绕过很多碍眼的内容，不断的在函数间进行跳转，使得排查问题的难度也成倍增加。

当然之所以导致这个问题，其实是因为这种嵌套的书写方式跟人线性的思考方式相违和，以至于要多花一些经历去思考真正的执行顺序，嵌套和缩进只是这个思考过程中转移注意力的细枝末节而已

当然了，与人线性的思考相违和，还不是最糟糕的，实际上，还会在代码中加入各种各样的逻辑判断，就比如在上面的那个例子中，doD()必须在 doC()完成之后才能完成，万一 doC()执行失败了呢？ 是要重试 doC()吗？还是直接转到其他处理处理函数中？ 当将这些判断都加入到这个流程中，很快代码就会变的非常复杂，以至于无法维护和更新

### 控制反转

正常书写代码的时候，理所当然可以控制自己的代码，然而当使用回调的时候，这个回调函数是否能接着执行，其实取决于使用回调的那个 API,就比如:

```js
// 回调函数是否执行取决于 buy 模块
import { buy } from "./buy.js"

buy(itemData, function (res) {
	console.log(res)
})
```

对于经常会使用 fetch 这种 API，一般是没有什么问题的，但是如果使用的是第三方的 API 呢？

当调用了第三方的 API，对方是否会因为某个错误导致你传入的回调函数执行了多次呢？

为了避免出现这样的问题，可以在自己的回调函数中加入判断，可是万一又因为某个错误导致这个回调函数没有执行呢？
万一这个回调函数有时同步执行有时异步执行呢？

总结一下这些情况:

1. 回调函数执行多次
2. 回调函数没有执行
3. 回调函数有时同步执行有时异步执行

对于这些情况，可能都要在回调函数中做些处理，并且每次执行回调函数的时候都要做些处理，这就带来了很多重复的代码

### 回调地狱

先看一个简单的回调地狱的示例

现在要找出一个目录中最大的文件，处理步骤如下:

1. 用`fs.readdir`获取目录中的文件列表
2. 循环遍历文件，使用`fs.stat`获取文件信息
3. 比较找出最大文件
4. 以最大文件的文件名为参数调用回调函数

```js
var fs = require("fs")
var path = require("path")

function findLargest(dir, cb) {
	// 读取目录下的所有文件
	fs.readdir(dir, function (er, files) {
		if (er) return cb(er)

		var counter = files.length
		var errored = false
		var stats = []

		files.forEach(function (file, index) {
			// 读取文件信息
			fs.stat(path.join(dir, file), function (er, stat) {
				if (errored) return

				if (er) {
					errored = true
					return cb(er)
				}

				stats[index] = stat

				// 事先算好有多少个文件，读完 1 个文件信息，计数减 1， 当为 0 时，进行最终比较操作
				if (--counter == 0) {
					var largest = stats
						.filter(function (stat) {
							return stat.isFile()
						})
						.reduce(function (prev, next) {
							if (prev.size > next.size) return prev
							return next
						})

					cb(null, files[stats.indexOf(largest)])
				}
			})
		})
	})
}
```

使用方式为:

```js
// 查找当前目录最大文件
findLargest("./", function (er, fileName) {
	if (er) return console.log(er)

	console.log("largest file was: ", fileName)
})
```

看完这个例子，接着说下回调地狱的其他问题:

1. 难以复用

回调的顺序确定下来之后， 想对其中某些环节进行复用也很困难，牵一发而动全身

举个例子， 如果你相对`fs.stat`读取文件信息这段代码复用，因为回调中引用了外层的变量， 提取出来后还需要对外层的代码进行修改

2. 堆栈信息被断开

JavaScript 引擎维护了一个执行上下文栈，当函数执行的时候，会创建该甘薯的执行上下文压入栈中，当函数执行完毕后，会将该执行上下文出栈

如果 A 函数中调用了 B 函数，JavaScript 会将 A 函数的执行上下文压入栈中，再讲 B 函数的执行上下文压入栈中，当 B 函数执行完毕，将 B 函数执行上下文出栈，当 A 函数执行完毕后，将 A 函数执行上下文出栈

这样的好处在于，如果中断代码执行，可以检索完整的堆栈信息，从中获取任何想要的获得的信息

可是异步回调函数并非如此，比如执行`fs.readdir`的时候，其实是将回调函数加入任务队列中，代码继续执行，直至主线程完成后，才会从任务队列中选择已经完成的任务，并将其加入栈中，此时栈中只有一个执行上下文,如果回调报错，也无法获取调用该异步操作时栈中的信息，不容易判断哪里出现了错误

此外，因为是异步的缘故，使用 try catch 语句也无法直接捕获错误

(不过 Promise 并没有解决这个问题)

3. 借助外层变量

当多个异步计算同时进行，比如这里遍历读取文件信息，由于无法预期完成顺序，必须借助外层作用域的变量，比如这里的 count、errored、stats 等，不仅写起来麻烦，而且如果你忽略了文件读取错误时的情况，不记录错误状态，就会接着读取其他文件，造成无谓的浪费。此外外层变量，也可能被其他同一作用域的函数访问并且修改，容易造成误操作

**之所以单独讲讲回调地狱，其实是想说嵌套的和缩进只是回调地狱的一个梗而已，它导致的问题远非嵌套导致的可读性降低而已**

## Promise

Promise 使得以上绝大部分的问题都得到了解决

1. 嵌套问题

举个例子:

```js
request(url, function (err, res, body) {
	if (err) handleError(err)
	fs.writeFile("1.txt", body, function (err) {
		request(url2, function (err, res, body) {
			if (err) handleError(err)
		})
	})
})
```

使用 Promise 后:

```js
request(url)
	.then(function (result) {
		return writeFileAsync("1.txt", result)
	})
	.then(function (result) {
		return request(url2)
	})
	.catch(function (e) {
		handleError(e)
	})
```

而对于读取最大文件的那个例子，可以使用 Promise 简化为:

```js
var fs = require("fs")
var path = require("path")

var readDir = function (dir) {
	return new Promise(function (resolve, reject) {
		fs.readdir(dir, function (err, files) {
			if (err) reject(err)
			resolve(files)
		})
	})
}

var stat = function (path) {
	return new Promise(function (resolve, reject) {
		fs.stat(path, function (err, stat) {
			if (err) reject(err)
			resolve(stat)
		})
	})
}

function findLargest(dir) {
	return readDir(dir)
		.then(function (files) {
			let promises = files.map((file) => stat(path.join(dir, file)))
			return Promise.all(promises).then(function (stats) {
				return { stats, files }
			})
		})
		.then((data) => {
			let largest = data.stats
				.filter(function (stat) {
					return stat.isFile()
				})
				.reduce((prev, next) => {
					if (prev.size > next.size) return prev
					return next
				})

			return data.files[data.stats.indexOf(largest)]
		})
}
```

2. 控制反转再反转

前面讲到使用第三方回调 API 的时候，可能会遇到如下问题:

1. 回调函数执行多次
2. 回调函数没有执行
3. 回调函数有时同步执行有时异步执行

对于第一个问题，Promise 只能 resolve 一次，剩下的调用都会被忽略

对于第二个问题，可以使用 Promise.race 函数来解决:

```js
function timeoutPromise(delay) {
	return new Promise(function (resolve, reject) {
		setTimeout(function () {
			reject("Timeout!")
		}, delay)
	})
}

Promise.race([foo(), timeoutPromise(3000)]).then(
	function () {},
	function (err) {}
)
```

对于第三个问题，为什么有的时候会同步执行，有的时候异步执行呢?

看个例子:

```js
var cache = {...}

function downloadFile(url) {
	if(cache.has(url)) {
		// 如果存在cache，这里为同步调用
		return cache.get(url)
	}
    return fetch(url).then(file => cache.set(url, file)); // 这里为异步调用
}
```

在这个例子中，有 cache 的情况下，会直接从返回 file，此时为同步调用，在没有 cache 的时候，是异步调用

然而如果这种同步和异步混用的代码作为内部实现，只暴露接口给外部调用，调用方由于无法判断到底是异步还是同步状态，影响程序的可维护性和可测试性

简单的来说就是同步和异步共存的情况无法保证程序逻辑的一致性

在不想区分函数是到底是是不是异步和同步的情况，可以使用 Promise 包装一下:

```js
Promise.resolve().then(downloadFile(url))
```

这样就将将这个函数都转为异步执行了， 但是又出现了一个问题，如果函数为同步函数，那么它会在本轮时间循环的末尾执行

那么如果想要同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API 呢?

那么可以用`new Promise()`来进行处理，因为`new Promise()`是会立即执行的

```js
const f = () => console.log("now")
;(() => new Promise((resolve) => resolve(f())))()
console.log("next")
```

上面的代码是使用了立即执行函数，执行`new Promise`，这种情况下同步函数也是同步执行的

::: info
需要注意的是，这里 f()函数是立即执行，但是 then 的执行一定是异步的，这是 Promise 中规范中有明确的规定
:::

## Promise 反模式

### Promise 嵌套

```js
// bad
loadSomething().then(function (something) {
	loadAnotherThing().then(function (another) {
		DoSomethingOnThem(something, another)
	})
})
```

```js
// good
Promise.all([loadSomething(), loadAnotherThing()]).then(function ([something, another]) {
	DoSomethingOnThem(...[something, another])
})
```

### 断开的 Promise 链

```js
// bad
function anAsyncCall() {
	var promise = doSomethingAsync()
	promise.then(function () {
		somethingComplicated()
	})

	return promise
}
```

```js
// good
function anAsyncCall() {
	var promise = doSomethingAsync()
	return promise.then(function () {
		somethingComplicated()
	})
}
```

注意`return`的位置，单独`return promise`会导致 then 后面的链断裂，再次使用`then`时，得到的只是`doSomethingAsync()`的结果

### 混乱的集合

```js
// bad
function workMyCollection(arr) {
	var resultArr = []
	function _recursive(idx) {
		if (idx >= resultArr.length) return resultArr

		return doSomethingAsync(arr[idx]).then(function (res) {
			resultArr.push(res)
			return _recursive(idx + 1)
		})
	}

	return _recursive(0)
}
```

可以写成:

```js
function workMyCollection(arr) {
	return Promise.all(
		arr.map(function (item) {
			return doSomethingAsync(item)
		})
	)
}
```

如果要以队列的形式执行，可以写成:

```js
function workMyCollection(arr) {
	return arr.reduce(function (promise, item) {
		return promise.then(function (result) {
			return doSomethingAsyncWithResult(item, result)
		})
	}, Promise.resolve())
}
```

### catch

```js
// bad
somethingAsync.then(
	function () {
		return somethingElseAsync()
	},
	function (err) {
		handleMyError(err)
	}
)
```

如果 somethingElseAsync 抛出错误，是无法被捕获的,可以写成:

```js
// good
somethingAsync
	.then(function () {
		return somethingElseAsync()
	})
	.then(null, function (err) {
		handleMyError(err)
	})
```

```js
// good
somethingAsync()
	.then(function () {
		return somethingElseAsync()
	})
	.catch(function (err) {
		handleMyError(err)
	})
```

这两种实际效果是相同的，catch 其实`then(null, function(err))`的另一种写法，基本上用 catch 就可以了

### 红绿灯的问题

题目：红灯三秒亮一次，绿灯一秒亮一次，黄灯 2 秒亮一次；如何让三个灯不断交替重复亮灯？（用 Promise 实现）

三个亮灯函数已经存在:

```js
function red() {
	console.log("red")
}
function green() {
	console.log("green")
}
function yellow() {
	console.log("yellow")
}
```

利用 then 和递归来实现

```js
var light = function (timer, cb) {
	return new Promise(function (resolve, reject) {
		setTimeout(function () {
			cb()
			resolve()
		}, timer)
	})
}

var step = function () {
	Promise.resolve()
		.then(function () {
			return light(3000, red)
		})
		.then(function () {
			return light(1000, green)
		})
		.then(function () {
			return light(2000, yellow)
		})
		.then(function () {
			step()
		})
}

step()
```

## promisify

有的时候，需要将 callback 语法的 API 改造成 Promise 语法，为此需要一个 promisify 的方法

因为 callback 语法传参比较明确，最后一个参数传入回调函数，回调函数的第一个参数是错误信息，如果没有错误就是 null,所以可以写出一个简单的 promisify 方法:

```js
function promisify(original) {
	return function (...args) {
		return new Promise((resolve, reject) => {
			args.push(function callback(err, ...values) {
				if (err) return reject(err)
				// 只能针对一个回调参数的情况，如果多参数需要用对象包裹起来
				// 这列只是简单的方法
				return resolve(...values)
			})

			original.call(this, ...args)
		})
	}
}
```

例子:

```js
var fs = require('fs')

// callback usage
fs.readdir('./', function (err, files) {
  ...
})

// promisify
let promisifyReadDir = promisify(fs.readdir)
promisifyReadDir('./').then(files => {
  console.log(files)
})
```

注意:

- fs.readdir 最后一个参数是回调函数
- 在进行 promisify 后，只传入前面的参数，不接收最后的回调函数
- promisify 内部再将回调参数使用 promise 接管
- 不同的回调函数参数结构, 需要额外的处理`resolve`和`reject`的时机

完整的可以参考[es6-promisify](https://github.com/digitaldesignlabs/es6-promisify/blob/master/lib/promisify.js)

## Promise 的局限性

### 错误被吃掉

首先要理解，什么是错误被吃掉,举个例子

```js
throw new Error("error")
console.log(2333)
```

在这种情况下，因为`throw error`的缘故，代码被阻断执行，并不会打印`2333`,再举个例子:

```js
const promise = new Promise(null)
console.log(2333)
```

以上代码依然会被阻断执行，只是因为如果通过无效的方式使用 Promise,并且出现了一个错误阻碍了正常 Promise 的构造，结果会得到一个立刻跑出的异常，而不是一个被拒绝的 Promise

然后再举个例子:

```js
let promise = new Promise(() => {
	throw new Error("error")
})
console.log(2333)
```

这次会正常打印`2333`，说明 Promise 内部的错误不会影响到 Promise 的代码，而这种情况通常就称为`吃掉错误`

其实这并不是 Promise 独有的局限性，`try...catch`也是这样，同样会捕获一个异常并简单的吃掉错误

正式因为错误被吃掉，Promise 链中的错误很容易被忽略，这也是为什么一般推荐在 Promise 链的最后添加一个 catch 函数，因为对于一个没有错误处理函数的 Promise 链，任何错误都会在链中被传递下去，直到你注册了错误处理函数

### 单一值

Promise 只要能有一个完成值或一个拒绝原因，然而在真实使用的时候，往往需要传递多个值，一般做法都是构造一个对象或数组，然后再传递，then 中获得这个值后，又会进行取值赋值的操作，每次封装和结构都无疑会让代码变得笨重

但是使用 ES6 结构赋值能够好很多:

```js
Promise.all([Promise.resolve(1), Promise.resolve(2)]).then(([x, y]) => {
	console.log(x, y)
})
```

### 无法取消

Promise 一但新建他就会立即执行，无法中途取消

### 无法得知 pending 状态

当处于 pending 状态时， 无法得知目前进展到哪一个阶段(刚刚开始即将完成)
